apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ikindle
type: Opaque
stringData:
  DB_USER: "ikindle"
  DB_PASSWORD: "ikindle_local_pwd"
  JWT_SECRET: "ikindleSecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKL"
  OSS_ENDPOINT: ""
  OSS_ACCESS_KEY_ID: ""
  OSS_ACCESS_KEY_SECRET: ""
  OSS_BUCKET: ""
  SMTP_HOST: "smtp.163.com"
  SMTP_PORT: "465"
  SMTP_USERNAME: "18659195904@163.com"
  SMTP_PASSWORD: "ZCbanwr5WefbQUeL"
  OAUTH_CLIENT_ID: "a91c9e88f4b842eca985"
  OAUTH_CLIENT_SECRET: "1bb56bc62e67493a95a5268530bb9397"
