apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
  namespace: ikindle
spec:
  ingressClassName: nginx
  rules:
    - host: admin.ikindle.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 80
